name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.7

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config

    - name: Terraform Init
      working-directory: ./terraform/dev
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform/dev
      run: terraform plan

    - name: Run Tests
      working-directory: ./terraform/dev
      run: |
        echo "Running tests..."
        terraform validate

    - name: Terraform Apply
      if: success()
      working-directory: ./terraform/dev
      run: terraform apply -var 'environment=dev' -auto-approve
