name: Deploy Microservices to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Ohio

    - name: Set up kubectl
      run: |
        aws eks update-kubeconfig --name t3.medium --region us-east-2

    - name: Set up Helm
      uses: azure/setup-helm@v2
      with:
        version: 'latest'

    - name: Deploy with Helm
      run: |
        helm upgrade --install my-microservice ./helm-charts/my-microservice

    - name: Set environment variable
      run: echo "MY_VAR=my_value" >> $GITHUB_ENV
