name: Deploy Microservices to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 # Ohio

    - name: Register Task Definition
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://ecs/task-definition.json

    - name: Update ECS Service
      run: |
        aws ecs update-service \
          --cluster my-cluster \
          --service my-microservice \
          --force-new-deployment
